services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    networks:
      - changedetection-net

  url-importer:
    container_name: url-importer
    build:
      context: .
      dockerfile: Dockerfile.importer
    depends_on:
      - changedetection
    env_file:
      - .env
    volumes:
      - ./importer-data:/app/data
    networks:
      - changedetection-net
    restart: "no"

volumes:
  changedetection-data:

networks:
  changedetection-net:
    driver: bridge